version: '2'
services:
  web:
    build: .
    ports:
      - 8080:80
    links:
      - db
      - redis
    env_file:
      - env
    volumes: 
      - ./app:/var/www/html/app
      - ./dev:/var/www/html/dev
      - ./pub/media:/var/www/html/pub/media
      - ./dev/tests/unit/phpunit.xml.dist:/var/www/html/dev/tests/unit/phpunit.xml.dist
      - ./composer.lock:/var/www/html/composer.lock
      - ./composer.json:/var/www/html/composer.json
    networks:
      env_net:
        ipv4_address: 172.10.1.1
   
  db:
    image: mysql:5.7.19
    volumes:
       - db-data:/var/lib/mysql
    ports:
       - 3306:3306 
    env_file:
      - env
    networks:
      env_net:
        ipv4_address: 172.10.1.2
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
    networks:
      env_net:
        ipv4_address: 172.10.1.3
      
  redis:
    image: redis     
    
volumes:
  db-data:
      
networks:
  env_net:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
